raw_data: Raw Datasets {
  CODE-15%
  SaMi-Trop
  PTB-XL
}

encoder: Resnet18-Encoder {
  shape: cylinder
}

classification: Classification {
  options: |md
    - Identity (no classification)
    - Weighted BCE Loss
    - Focal Loss
    - RAT Loss
  |
}

projection: Projection {
  output_dim: 128
}

embeddings: Embeddings (512-dim)

raw_data -> encoder
encoder -> embeddings
embeddings -> classification
embeddings -> projection

classification -> chagas probability
projection -> projection metrics (GPU, SAA, CAC)

embeddings -> UMAP visualizations
