seed_everything: 42

trainer:
  accelerator: auto            # or "gpu"/"cpu"
  devices: 1
  max_epochs: 25
  precision: bf16-mixed
  accumulate_grad_batches: 2
  limit_train_batches: 1.0      # or 0.1 for CPU debugging
  limit_val_batches: 1.0
  enable_model_summary: true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: PhysioNetChallenge25
      entity: ag-lukassen
      save_dir: wandb
      log_model: all
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_score
        mode: max
        dirpath: ${model_folder:-model}   # or a literal path
        filename: best_ep_{epoch}_score_{val_score:.3f}
        save_top_k: 1
        save_weights_only: false
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

model:
  lr: 0.0001
  num_classes: 1
  channels: 12
  norm_type: group
  norm_groups: 4

data:
  meta_path: /home/flo178/projects/master-thesis/datasets/physionet2025/metadata_official_clean_v3.csv
  data_dir: /home/flo178/projects/master-thesis/datasets/physionet2025/processedOfficialCleanV3
  batch_size: 32
  num_workers: 0
  pos_fraction: 0.25
  oversample: false
  train_folds: [0] # [0,1,2,3]
  valid_folds: [4]

seed_everything: 42

trainer:
  accelerator: cpu
  devices: 1
  max_epochs: 1
  precision: 32
  logger: null
  enable_checkpointing: false

model:
  lr: 0.0001
  num_classes: 1
  channels: 12
  norm_type: group
  norm_groups: 4

data:
  meta_path: /home/flo178/projects/master-thesis/datasets/physionet2025/metadata_official_clean_v3.csv
  data_dir: /home/flo178/projects/master-thesis/datasets/physionet2025/processedOfficialCleanV3
  batch_size: 32
  num_workers: 0
  pos_fraction: 0.25
  oversample: false
  train_folds: [0] # [0,1,2,3]
  valid_folds: [4]
