direction: right

# raw_data: ECG
prepro: ECG Preprocessing\n(Harmonization) {
  style.shadow: true
  bandpass: 1: Bandpass (BP)
  + softclip: 2: BP\n+ Softclip (SC)
  + normalize: 3: BP + SC\n+ Normalize (NORM)
}

encoder: Encoder\n(shared representation) {
  shape: image
  icon: plot_encoder.png
  height: 250
  width: 250
}

heads: Learning / Loss Strategies {
  style.shadow: true
  classification: Classification Head {
    options: |`md
      | Method |
      | :--- |
      | W-BaCE |
      | Focal |
      | RAT |
    `|
    metrics: |`md
      | Metric |
      | :--- |
      | TPR @5% |
      | pAUC @5% |
      | AP |
    `|
  }

  projection: Projection Head {
    options: |`md
      | Method |
      | :--- |
      | SupCon |
      | SupMin |
      | SupProto |
    `|
    metrics: |`md
      | Metric |
      | :--- |
      | GPU |
      | CAC |
      | SAA |
    `|
  }
}

run_analysis: Post-Hoc Analysis\nPer-Model {
  style.shadow: true
  grid-columns: 1
  Task Utility (Ranking) -- Embedding Space Health -- Physiological Plausibility
  x: |md
    ---
  |
  Cross-Model Consistency\n(post-selection)
}

# raw_data -> prepro.bandpass
# raw_data -> prepro.+ softclip
# raw_data -> prepro.+ normalize
prepro.bandpass -> encoder
prepro.+ softclip -> encoder
prepro.+ normalize -> encoder
encoder -> heads.classification: shaped by
encoder -> heads.projection: shaped by

heads.classification.options -> heads.classification.metrics: eval w/ {
  style.stroke-dash: 3
}
heads.projection.options -> heads.projection.metrics: eval w/ {
  style.stroke-dash: 3
}
heads.classification -> run_analysis
encoder -> run_analysis
heads.projection -> run_analysis
