# latexmk config for thesis builds (used by LaTeX Workshop and CLI).

$pdf_mode = 1;
$interaction = "nonstopmode";
$halt_on_error = 1;

$out_dir = ".out";

# Prefer LuaLaTeX by default; switch to xelatex if you prefer.
$pdflatex = "lualatex %O %S";

# biblatex
$bibtex = "biber %O %B";

add_cus_dep("glo", "gls", 0, "makeglossaries");
sub makeglossaries {
  system("makeglossaries '$_[0]'");
}

